// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniDziennik.Context;

namespace MiniDziennik.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20220404100942_migracja")]
    partial class migracja
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("MiniDziennik.Model.Klasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazwaKlasy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Klasa");
                });

            modelBuilder.Entity("MiniDziennik.Model.Uczniowie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imie")
                        .HasColumnType("TEXT");

                    b.Property<int>("KlasaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("TEXT");

                    b.Property<int>("RokUrodzenia")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KlasaId");

                    b.ToTable("Uczniowie");
                });

            modelBuilder.Entity("MiniDziennik.Model.Uczniowie", b =>
                {
                    b.HasOne("MiniDziennik.Model.Klasa", "Klasa")
                        .WithMany()
                        .HasForeignKey("KlasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klasa");
                });
#pragma warning restore 612, 618
        }
    }
}
